# Generated by Django 4.1.13 on 2024-11-16 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('cmd', models.TextField(blank=True, null=True)),
                ('expect_output', models.TextField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='category.category')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combine', models.CharField(choices=[('AND', 'And'), ('OR', 'Or')], max_length=3)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('scored', models.BooleanField(default=False)),
                ('remediation', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='category.category')),
            ],
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('Equal', 'Equal'), ('Contain', 'Contain'), ('Not contain', 'Not contain'), ('Include one of', 'Include one of'), ('All in', 'All in'), ('Not equal', 'Not equal'), ('Permission lower or equal', 'Permission lower or equal'), ('Regex', 'Regex'), ('Greater Than', 'Greater Than'), ('Greater Than Or Equal', 'Greater Than Or Equal'), ('Less Than', 'Less Than'), ('Less Than Or Equal', 'Less Than Or Equal'), ('Between', 'Between')], max_length=255)),
                ('cmd', models.TextField()),
                ('expect', models.TextField()),
                ('parser', models.TextField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='category.task')),
            ],
        ),
    ]
